# Generated by Django 6.0.4 on 2026-05-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesmentor',
            name='course_date',
            field=models.DateField(verbose_name='старт'),
        ),
        migrations.AlterField(
            model_name='coursesmentor',
            name='mentor',
            field=models.CharField(max_length=50, verbose_name='ментор'),
        ),
        migrations.AlterField(
            model_name='coursesmentor',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название курса'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='avatar',
            field=models.ImageField(upload_to='media/', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor_course', to='mentors.coursesmentor', verbose_name='группа ментора'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='phone_number',
            field=models.IntegerField(verbose_name='номер телефона'),
        ),
    ]
