# Generated by Django 6.0.4 on 2026-05-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mentor', models.CharField(max_length=50)),
                ('course_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='media/')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_course', to='students.coursesstudent')),
            ],
        ),
    ]
