# Generated by Django 6.0.4 on 2026-05-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesstudent',
            name='course_date',
            field=models.DateField(verbose_name='старт'),
        ),
        migrations.AlterField(
            model_name='coursesstudent',
            name='mentor',
            field=models.CharField(max_length=50, verbose_name='ментор'),
        ),
        migrations.AlterField(
            model_name='coursesstudent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название курса'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(upload_to='media/', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_course', to='students.coursesstudent', verbose_name='группа'),
        ),
    ]
